### ISSUE TITLE
DBI specification

### ISSUE THREAD

**Issue by krlmlr** [terrytangyuan/ctv-databases#1]
I wonder if this should be discussed/pointed to in this task view. Some packages try to follow it (among these RPostgres and RGreenplum which seem to be missing for now), many existing packages won't.

**Comment by terrytangyuan** [comment]
I've addressed this by:
* adding a note to DBI description
* moving DBI to top of the list
* adding "DBI-compliant" to the description of the packages that follow DBI interface

Let me know if I miss anything. Thanks again!
