### ISSUE TITLE
adding spark tools

### ISSUE THREAD

**Issue by ColinFay** [terrytangyuan/ctv-databases#12]
Would `{SparkR}` and `{sparklyr}` be a good fit for this task view ?

**Comment by terrytangyuan** [comment]
I thought about this again and realized that `sparklyr` might be a good fit. Feel free to send a PR for this! Otherwise, I'll add it when I get a chance.

**Comment by terrytangyuan** [comment]
cc: @javierluraschi @kevinykuo @kevinushey @jjallaire

**Comment by terrytangyuan** [comment]
Added in https://github.com/terrytangyuan/ctv-databases/commit/c6caeb40c56cacb2165bd2baa469bb7600498fe9.
