### ISSUE TITLE
Add dbx to the list

### ISSUE THREAD

**Issue by terrytangyuan** [terrytangyuan/ctv-databases#13]
https://github.com/ankane/dbx

cc @ankane Feel free to send a PR for this! Otherwise, I'll add it when I get a chance.

**Comment by terrytangyuan** [comment]
Added in https://github.com/terrytangyuan/ctv-databases/commit/c6caeb40c56cacb2165bd2baa469bb7600498fe9.

**Comment by ankane** [comment]
Thanks @terrytangyuan!
