### ISSUE TITLE
Shop in packages that import DBI

### ISSUE THREAD

**Issue by krlmlr** [terrytangyuan/ctv-databases#2]
"Reverse imports" on https://cran.r-project.org/web/packages/DBI/index.html.

I think most packages there are relevant for this task view. Here, we can offer the list of packages in a more structured and topic-oriented way.

**Comment by terrytangyuan** [comment]
Thanks for the suggestion! I've selected and added the related packages, excluding the research/application specific packages, e.g. acc package that "processes accelerometer data from uni-axial and tri-axial devices, and generates data summaries. Also includes functions to plot, analyze, and simulate accelerometer data". I think it's not very relevant to this task view and the list can go on forever. Let me know if I miss anything else.
